title: Destin's Desk
author: Destin Coleman
email: destin_c@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
 Where the magic happens

# social links
twitter_username: your-twitter-handle
github_username: destinc 

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
